---
# file: tasks/install.yml
# Top-level installer for Oracle JDK.
#

- name: mkdir for Java
  file:
    path: "{{ java_install_path }}"
    state: directory

- name: check jdk variable 
  shell: cat ~/.bash_profile 
  register: result

- name: install JDK via tarball file
  unarchive:
    src: "{{ jdk_tarball_file }}.tar.gz"
    dest: "{{ java_install_path }}"
  failed_when: result.stdout.find('JAVA_HOME') != -1

- name: jdk variable configuration ~/.bash_profile file
  shell: /bin/echo {{ item }} >> ~/.bash_profile; source ~/.bash_profile
  failed_when: result.stdout.find('JAVA_HOME') != -1
  with_items:
     - export JAVA_HOME={{ java_install_path }}/jdk{{ jdk_version }}
     - export JRE_HOME=\$JAVA_HOME/jre
     - export PATH=\$PATH:\$JAVA_HOME/bin:\$JRE_HOME/bin
     - export CLASSPATH=.:\$JAVA_HOME/lib:\$JRE_HOME/lib
     - export JAVA_HOME PATH JRE_HOME CLASSPATH
