---
- hosts: all 
  gather_facts: no
  vars:
    - fixed:
        mysql_port: 3306
  tasks:
  - name: check openssl_devel
    shell: rpm -qa|grep openssl-devel
    ignore_errors: True
  
  - name: check gcc_gcc_c++
    shell: rpm -qa|grep gcc 
    ignore_errors: True

  - name: check make
    shell: rpm -qa|grep make
    ignore_errors: True
 
  - name: check dmdb_port
    wait_for: port={{ mysql_port }} timeout=1
    ignore_errors: True

  - name: check keepalived ipvsadm
    shell: rpm -qa|grep ipvsdm
    ignore_errors: True

  - name: check keepalived popt_devel
    shell: rpm -qa|grep popt-devel
    ignore_errors: True
