---

- name: upload mysql.server
  template:
    src: "my.cnf"
    dest: "~/.my.cnf"
    mode: 0640
  delegate_to: "{{master1}}"
  run_once: true

- name: upload mysql-slave.server
  template:
    src: "my-slave.cnf"
    dest: "~/.my.cnf"
    mode: 0640
  delegate_to: "{{master2}}"
  run_once: true

- name: create log directory if it does not exist
  file:
    state: directory
    path: "{{ mysql_dir}}/mysql/log"

- name: mysql initialize
  shell: ./mysqld  --user={{user}} --initialize-insecure
  args:
    chdir: "{{ mysql_dir }}/mysql/bin"

- name: mysql start
  shell: ./mysqld_safe  --defaults-file=~/.my.cnf --user={{user}} &
  args:
    chdir: "{{ mysql_dir }}/mysql/bin"

- name: grant replication slave
  shell: echo "grant replication slave on *.* to 'repluser'@'{{master2}}' IDENTIFIED BY 'slavepass'" | ./mysql -uroot
  args:
    chdir: "{{ mysql_dir }}/mysql/bin"
  delegate_to: "{{master1}}"
  run_once: true

- name: get master1 file and position info
  shell: |
    master_info=$(echo "show master status\G"  | ./mysql -uroot)
    masters=($master_info)
    mnum="${{"{"}}#masters[@]}"
    filenum=0
    position=0
    for((i=0;i<mnum;i++))
      do
        if [ "File:" == "${masters[$i]}" ]
         then filenum=$(($i+1))
        elif [ "Position:" == "${masters[$i]}" ]
         then position=$(($i+1))
        fi
      done
    echo ${masters[$filenum]}
    echo ${masters[$position]}
  args:
    chdir: "{{ mysql_dir }}/mysql/bin"
  delegate_to: "{{master1}}"
  run_once: true
  register: loginfo
  delegate_to: "{{master1}}"
  run_once: true


- name: config master1 into to master2
  shell: |
    loginfo="{{loginfo.stdout_lines}}"
    loginfo_forshell=$(echo "$loginfo" | sed "s|\[||g" | sed "s|'||g" |sed  "s|\]||g" |sed "s| ||g" | sed "s|u||g")
    OLD_IFS="$IFS"
    IFS=","
    infos=($loginfo_forshell)
    IFS="$OLD_IFS"
    echo "change master to master_host='{{master1}}',master_user='repluser',master_password='slavepass',master_log_file='${infos[0]}',master_log_pos=${infos[1]}" | ./mysql -uroot
    echo "slave start"  | ./mysql -uroot
  args:
    chdir: "{{ mysql_dir }}/mysql/bin"
  delegate_to: "{{master2}}"
  run_once: true


- name: grant replication slave
  shell: echo "grant replication slave on *.* to 'repluser'@'{{master1}}' IDENTIFIED BY 'slavepass'" | ./mysql -uroot
  args:
    chdir: "{{ mysql_dir }}/mysql/bin"
  delegate_to: "{{master2}}"
  run_once: true


- name: get master2 file and position info
  shell: |
    master_info=$(echo "show master status\G"  | ./mysql -uroot)
    masters=($master_info)
    mnum="${{"{"}}#masters[@]}"
    filenum=0
    position=0
    for((i=0;i<mnum;i++))
      do
        if [ "File:" == "${masters[$i]}" ]
         then filenum=$(($i+1))
        elif [ "Position:" == "${masters[$i]}" ]
         then position=$(($i+1))
        fi
      done
    echo ${masters[$filenum]}
    echo ${masters[$position]}
  args:
    chdir: "{{ mysql_dir }}/mysql/bin"
  delegate_to: "{{master2}}"
  run_once: true
  register: masterloginfo
  delegate_to: "{{master2}}"
  run_once: true


- name: config master2 into to master1
  shell: |
    loginfo="{{masterloginfo.stdout_lines}}"
    loginfo_forshell=$(echo "$loginfo" | sed "s|\[||g" | sed "s|'||g" |sed  "s|\]||g" |sed "s| ||g" | sed "s|u||g")
    OLD_IFS="$IFS"
    IFS=","
    infos=($loginfo_forshell)
    IFS="$OLD_IFS"
    echo "slave stop"  | ./mysql -uroot
    echo "change master to master_host='{{master2}}',master_user='repluser',master_password='slavepass',master_log_file='${infos[0]}',master_log_pos=${infos[1]}" | ./mysql -uroot
    echo "slave start"  | ./mysql -uroot
  args:
    chdir: "{{ mysql_dir }}/mysql/bin"
  delegate_to: "{{master1}}"
  run_once: true