---
- set_fact: redis_user="{{ redis_user|default(ansible_user_id) }}"
- set_fact: redis_group="{{ redis_group|default(ansible_user_gid) }}"
- set_fact: home="{{ ansible_user_dir }}"

- include: upload.yml
  when:
    - upload ==True
    - cluster == False

- include: cluster.yml
  when:
    - upload ==False
    - cluster == True

- include: clusterInfo.yml
  when:
    - upload == False
    - cluster == False
